

CREATE TABLE CATEGORIA
( 
	IDCATEGORIA          integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCATEGORIA PRIMARY KEY (IDCATEGORIA ASC)
)
go



CREATE TABLE PRODUCTO
( 
	IDPRODUCTO           integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	IDCATEGORIA          integer  NOT NULL ,
	PRECIO               numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKPRODUCTO PRIMARY KEY (IDPRODUCTO ASC),
	CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE CLIENTE
( 
	IDCLIENTE            integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	DIRECCION            varchar(100)  NOT NULL ,
	CORREO               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCLIENTE PRIMARY KEY (IDCLIENTE ASC)
)
go



CREATE TABLE VENTA
( 
	IDVENTA              integer IDENTITY ( 1,1 ) ,
	IDCLIENTE            integer  NOT NULL ,
	FECHA                datetime  NULL ,
	IDPRODUCTO           integer  NOT NULL ,
	PRECIO               numeric(10,2)  NOT NULL ,
	CANTIDAD             integer  NOT NULL ,
	IMPORTE              numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKVENTA PRIMARY KEY (IDVENTA ASC),
	CONSTRAINT FK_VENTA_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go


