--
--PROBLEMA: N°1 
--DESARROLLAR UNA CONSULTA QUE PERMITA ENCONTRAR TODOS LOS EMPLEADOS QUE NO TIENEN TELÉFONO. BASE DE DATOS: RH
-- 
USE RH
--
SELECT * FROM EMPLEADO
--
SELECT IDEMPLEADO,NOMBRE,APELLIDO, TELEFONO = 'NULL' FROM EMPLEADO
GO

--************************************************************************************************************************************
--
--PROBLEMA: N°2 
--DESARROLLAR UNA CONSULTA PARA ENCONTRAR LOS INGRESOS TOTALES DE CADA UNO DE LOS EMPLEADOS. BASE DE DATOS: RH
--
USE RH
--
SELECT * FROM EMPLEADO
--
SELECT  IDEMPLEADO,NOMBRE,APELLIDO, SUM(SUELDO + COMISION) AS 'INGRESOS TOTALES'  FROM EMPLEADO GROUP BY IDEMPLEADO,NOMBRE,APELLIDO
GO
--
--************************************************************************************************************************************
--
--PROBLEMA: N°3 
--DESARROLLAR UNA CONSULTA PARA ENCONTRAR A TODOS LOS EMPLEADOS QUE NO TIENEN CORREO INSTITUCIONAL. 
--EL DOMINIO DEL CORREO INSTITUCIONAL PUEDE SER PERUDEV.COM O PERUDEV.PE. DE BASE DE DATOS: RH 
--
USE RH
--
SELECT * FROM EMPLEADO
--
SELECT IDEMPLEADO,NOMBRE,APELLIDO,EMAIL FROM EMPLEADO WHERE EMAIL  = 'GCORONELC@GMAIL.COM' 
GO
--
--*************************************************************************************************************************************
--
--PROBLEMA: N°4 
--DESARROLLAR UNA CONSULTA QUE PERMITA ENCONTRAR EL TIEMPO DE SERVICIO EN MESES DE CADA EMPLEADO. 
--BASE DE DATOS: RH
--
USE RH
--
SET DATEFORMAT DMY
SELECT * FROM EMPLEADO
-- 
SELECT  IDEMPLEADO,NOMBRE,APELLIDO, DATEDIFF(YEAR,FECINGRESO,GETDATE()) AS 'TIEMPO AÑOS'  FROM EMPLEADO
GO

--
--************************************************************************************************************************************
--
--PROBLEMA: N°5 
--SE NECESITA SABER LA PROGRAMACIÓN DEL PROFESOR RAÚL CHUCO EN EL PRESENTE MES. 
--BASE DE DATOS: EDUTEC 
--
USE EDUTEC
--
SELECT * FROM CURSOPROGRAMADO
SELECT * FROM PROFESOR
--
SELECT C.HORARIO,P.IDPROFESOR,P.APEPROFESOR,P.NOMPROFESOR FROM PROFESOR P
INNER JOIN CURSOPROGRAMADO C ON P.IDPROFESOR = C.IDPROFESOR
WHERE P.IDPROFESOR = 'P011' AND IDCICLO = '2021-02-01'
--
--***********************************************************************************************************************************
--
--PROBLEMA 6 
--SE NECESITA SABER QUE PROFESORES VIVEN EN SMP, EN LOS OLIVOS O EN COMAS. 
--BASE DE DATOS: EDUTEC
--
USE EDUTEC
--
SELECT * FROM PROFESOR
--
SELECT IDPROFESOR,APEPROFESOR,NOMPROFESOR,DIRPROFESOR   FROM PROFESOR
WHERE DIRPROFESOR = 'SMP' OR DIRPROFESOR ='COMAS' OR DIRPROFESOR = 'LOS OLIVOS'
--
--*************************************************************************************************************************************
--
--PROBLEMA 7 
--SE NECESITA SABER LOS CURSOS PROGRAMADOS PARA ESTE MES QUE TIENEN MENOS DE 10 MATRICULADOS. 
--
USE EDUTEC
--
SELECT * FROM CURSOPROGRAMADO
--
SELECT IDCURSO,IDPROFESOR,MATRICULADOS FROM CURSOPROGRAMADO
WHERE MATRICULADOS < 10 and IDCICLO = '2021-02-01' ORDER BY MATRICULADOS DESC
--
--*************************************************************************************************************************************
--
--PROBLEMA 8 
--SE NECESITA SABER LOS HORARIOS EN QUE HAN SIDO PROGRAMADOS LOS CURSOS DE JAVA EN EL MES ACTUAL. 
--BASE DE DATOS: EDUTEC 
--
USE EDUTEC
--
SELECT * FROM CURSOPROGRAMADO
SELECT * FROM CURSO
--
SELECT CP.IDCICLO,C.IDCURSO,C.NOMCURSO FROM CURSO C
INNER JOIN CURSOPROGRAMADO CP ON C.IDCURSO = CP.IDCURSO
WHERE  C.IDCURSO = 'C005' OR C.IDCURSO = 'C006' OR C.IDCURSO = 'C007' 
OR C.IDCURSO = 'C008'OR C.IDCURSO = 'C0014'
AND CP.IDCICLO = ('2021-02')
GO
--
--************************************************************************************************************************************
--
--PROBLEMA 9 
--SE NECESITA UNA CONSULTA PARA AVERIGUAR LOS PEDIDOS QUE SERÁN LLEVADOS A MÉXICO, ESPAÑA Y BRASIL. 
--BASE DE DATOS: NORTHWIND 
--
USE NORTHWIND
--
SELECT * FROM ORDERS
--
SELECT ORDERID,CUSTOMERID,ORDERDATE,SHIPNAME,SHIPREGION,SHIPCOUNTRY FROM ORDERS
WHERE SHIPCOUNTRY IN ('MEXICO','ESPAÑA','BRAZIL')
--
--***********************************************************************************************************************************
--
--PROBLEMA 10 
--SE NECESITA UNA CONSULTA DE LOS CLIENTES DE LAS SIGUIENTES CIUDADES: 
--▪	RIO DE JANEIRO 
--▪	SAO PAULO 
--▪	BUENOS AIRES 
--▪	CARACAS 
--BASE DE DATOS: NORTHWIND 
--
USE NORTHWIND
--
SELECT * FROM CUSTOMERS
--
SELECT CUSTOMERID,COMPANYNAME,CONTACTNAME,COUNTRY,CITY FROM CUSTOMERS
WHERE CITY ='RIO DE JANEIRO' OR CITY ='SAO PAULO' OR CITY ='BUENOS AIRES' OR
CITY ='CARACAS'
--
--**********************************************************************************************************************************
--
--PROBLEMA 11 
--SE NECESITA UN LISTADO DE LAS CIUDADES DONDE SE TIENEN CLIENTES. 
--BASE DE DATOS: NORTHWIND 
--
USE NORTHWIND
--
SELECT * FROM CUSTOMERS
SELECT * FROM SUPPLIERS
--
SELECT  CONTACTNAME,COMPANYNAME,CITY FROM CUSTOMERS WHERE CITY = '*'
--
--***********************************************************************************************************************************
--
--PROBLEMA 12 
--SE NECESITA UN LISTADO DE LOS CLIENTES, CUYO REPRESENTANTE ES EL GERENTE DE VENTAS, EL GERENTE DE MARKETING O EL MISMO DUEÑO. 
--BASE DE DATOS: NORTHWIND 
--
USE NORTHWIND
--
SELECT * FROM CUSTOMERS
--
SELECT CUSTOMERID,CONTACTNAME,CONTACTTITLE FROM CUSTOMERS 
WHERE CONTACTTITLE='SALES MANAGER' OR CONTACTTITLE='MARKETING MANAGER' OR CONTACTTITLE='OWNER'
--
--************************************************************************************************************************

